<a href="https://colab.research.google.com/github/VikramxD/Data-Science-Fundamentals/blob/gh-pages/Generate__Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
20*np.ones((2,3))

array([[20., 20., 20.],
       [20., 20., 20.]])

In [16]:
np.random.randn(30,40)

array([[-0.45410104,  0.69471226, -0.20132011, ..., -0.63113122,
        -1.49928428,  0.85988315],
       [ 1.94207044, -0.09228541, -0.06878558, ..., -1.36200816,
         0.89726415, -0.0792569 ],
       [ 0.90848624,  0.58910119,  0.46830577, ...,  0.6885358 ,
        -0.7936376 , -1.85045209],
       ...,
       [-1.10286781,  0.27252937, -0.74566194, ..., -0.9994728 ,
        -0.01927335,  0.0609656 ],
       [-0.53090217,  0.52436824, -0.32779634, ..., -1.14605288,
        -0.03783711, -0.12563684],
       [-0.48771147,  0.07705838,  0.21371843, ...,  1.72008276,
         0.20859031,  0.13396097]])

In [21]:
R=np.random.randn(100000)

In [22]:
R.mean()

0.0051208404212126106

In [23]:
R.var()

1.0004817885632258

In [24]:
R.std()

1.0002408652735728

In [25]:
R=np.random.randn(20020,45)

In [26]:
R

array([[-2.75971653, -0.14279288,  1.1524316 , ..., -0.54307692,
        -2.29485514, -2.29222159],
       [-0.97204582,  0.86390725,  1.01269678, ..., -0.19261213,
        -0.28960872,  0.01458104],
       [ 0.44741896, -1.39419526, -1.3825289 , ..., -1.22083189,
         0.02234764,  1.12598883],
       ...,
       [-1.14123302, -0.54532376,  0.18615096, ..., -1.57869188,
        -0.63964449, -0.69993278],
       [-0.74596303,  0.16753419, -0.57811149, ...,  1.14627793,
         0.54690452,  1.19792522],
       [ 0.18160668, -0.69127596, -0.70654896, ..., -0.8457718 ,
         0.76358396,  1.05777897]])

In [28]:
Array=np.random.randint(1,100,3)

In [29]:
Array

array([22, 76, 83])