In [2]:
!pip install watermark

In [3]:
!pip install numpy scipy matplotlib
!pip install numpy scipy matplotlib

In [4]:
%load_ext watermark

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


**Numpy Approach** is better and efficient only comes as loss of using numpy arrays as homogenous and limited array

In [6]:
large_a=np.arange(1000)
large_b=np.arange(1000)
%timeit np.dot(large_a,large_b)

The slowest run took 28.36 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.13 µs per loop


**We also can create a list with N-dimensions in Numpy** easy and Convinient 


In [7]:
list_Convert=[[12,22,3,44],[12,2,33,1]]
Array=np.array(list_Convert)
Array

array([[12, 22,  3, 44],
       [12,  2, 33,  1]])

In [8]:
#for returning the number of dimensions in the array
np.ndim(Array)

2

In [9]:
#for finding the shape of the array
np.shape(Array)

(2, 4)

**Array construction in Numpy**

In [10]:
#Basic Placeholder arrays useful for later computations 
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#Identity Matrix in Numpy
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#An Array with Diagonal elements
np.diag([3,3,3])


array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [14]:
np.arange(0,22,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

## Array Operations and Universal Functions
**+ ,- , / ,* ,  ^  , log**

In [15]:
A=np.array([122,22,3,10,5,6])
B=np.array([2334,223,4,45,5,6])

In [16]:
np.add(A,1)

array([123,  23,   4,  11,   6,   7])

In [17]:
A*4

array([488,  88,  12,  40,  20,  24])

In [18]:
A**B

array([                 0,                  0,                 81,
       802379605485813760,               3125,              46656])

In [19]:
np.add.reduce(A,axis=0)

168

**Indexing the arrays--Memory Views and Memory Copies**

In [20]:
 #Boolean Array
 ary=np.array([12,33,4,5,6,1])
 ary_greater_3=ary>3
 ary_greater_3

array([ True,  True,  True,  True,  True, False])

In [21]:
ary[(ary>3) & (ary%2==0)]

array([12,  4,  6])

##Random Number Generators
useful for early prototyping and gap filling and Hypothesis

In [22]:
np.random.seed(121)                                                                                                                                       #seed value finalizes the result so that makes our code reusable and producable


np.random.rand(3)

array([0.11133083, 0.21076757, 0.23296249])

## Reshaping Numpy Arrays 


In [23]:
row_vector=np.array([12,23,4,5])
row_vector

array([12, 23,  4,  5])

In [25]:
column_vector=np.array([[1,3,4,56,78]]).reshape(-1,1)
column_vector

array([[ 1],
       [ 3],
       [ 4],
       [56],
       [78]])

In [36]:
A=np.transpose(column_vector)

In [29]:
matrix=np.array([[12,23,4,5,6,67],[54,32,67,8,76,65]])
matrix

array([[12, 23,  4,  5,  6, 67],
       [54, 32, 67,  8, 76, 65]])

In [37]:
np.matmul(column_vector, A)

array([[   1,    3,    4,   56,   78],
       [   3,    9,   12,  168,  234],
       [   4,   12,   16,  224,  312],
       [  56,  168,  224, 3136, 4368],
       [  78,  234,  312, 4368, 6084]])