<a href="https://colab.research.google.com/github/VikramxD/Data-Science-Fundamentals/blob/gh-pages/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
List=[[12,31],[32,45]]

In [8]:
List[1][0]

32

In [18]:
#Numpy Array Functions
A=np.array([[12,31],[32,45]])

In [22]:
A

array([[12, 31],
       [32, 45]])

Array Methods in Numpy

In [21]:
A.T

array([[12, 32],
       [31, 45]])

In [23]:
np.exp(A)

array([[1.62754791e+05, 2.90488497e+13],
       [7.89629602e+13, 3.49342711e+19]])

In [26]:
np.arccosh(A)

array([[3.17631318, 4.12687414],
       [4.15863885, 4.49968619]])

In [28]:
A.dot(A)

array([[1136, 1767],
       [1824, 3017]])

In [29]:
np.linalg.det(A)

-452.00000000000017

In [32]:
B=np.linalg.inv(A)

In [37]:
(A*B).sum()

2.0022123893805306

In [34]:
np.trace(A)

57