<a href="https://colab.research.google.com/github/VikramxD/Data-Science-Fundamentals/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
Fruits = [1,2,3,4,5,6,7,]


In [ ]:
Fresh= np.array(Fruits)
Fresh

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
for F in Fresh:
  print(F)

1
2
3
4
5
6
7


In [ ]:
Fresh=Fruits+np.array([4])


Broadcasting 

In [ ]:
Fresh

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
L2=[]
for F in Fruits:
  L2.append(F**2)

In [ ]:
L2

[1, 4, 9, 16, 25, 36, 49]

In [ ]:
Fresh**2

array([ 25,  36,  49,  64,  81, 100, 121])

In [ ]:
np.exp(Fresh)

array([  148.4131591 ,   403.42879349,  1096.63315843,  2980.95798704,
        8103.08392758, 22026.46579481, 59874.1417152 ])

In [ ]:
np.tanh(Fresh)

array([0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997,
       1.        , 1.        ])

In [ ]:
np.cosh(Fresh)

array([   74.20994852,   201.71563612,   548.31703516,  1490.47916125,
        4051.54202549, 11013.2329201 , 29937.07086595])

In [ ]:
np.sinh(Fresh)

array([   74.20321058,   201.71315737,   548.31612327,  1490.47882579,
        4051.54190208, 11013.2328747 , 29937.07084925])